 type = "service_account"
project_id = "sptpl-452205"
private_key_id = "1e66df629e9d10276e2597131c9940536ce1d7db"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDIIsrb1IGXf+36
Ei5ECYbqo26kacds3vW2/S4X92sLX4yCMF9bmw/EPSZGBmuOdCH/lhAqPOv0s2KL
Dw2Co9j7Pf8F+U6rnvg10z6R3N0bMy5ItJbamCuPut93YB2KE6WW2e4e/vNgGMe/
cmmycAf4uAUvL+SrFev/1NQF4riI4B70lzolPElNr2kPGDpchQsCkRPDNx0ZUG1G
f+oyhSebKXHkYTMuwCIifGk8H0CZHPQToR8f13VpG8zDpwXpqkEtyvy2dq8Q2400
yixgVJDhM/AN87FKxfXrAdQVCpL/tCuN4iYscFSu3tz/WcDW5NKcHnpUwlpeOoAQ
v/Jlf3aZAgMBAAECggEAI5CtQIID0oahJXCgKKaRw3YuFgkXL6VygGV/ELK+4stE
xqjudTK5y0t7lvOSnwLLvOXvsvXXD4nmP+R5p+bSixlCDc93N7/dB4Gl65lWcHw4
pCJ1cVyb1yOkDQx3S1+A7G0HaBox6TiWHJMqLdPDUuNuxmsqJW4UnYa2c+JNnUL3
9RfD3ghWNF4uI09NzCpcdw+5JwZ3ITNrcSGzCp+YuWbV2vDR42Zx9offYNBDKAeK
ia0s4pLgB+6nQb0MBDKaVeNdYclpgg2+1UjMKYBkb9j6ezX894F9oBqQxHfQxVCF
3OuBn7Dg2ilaVZkUk4AFnolvomolpg/HVuKbccYXJQKBgQD21lKE7eDA/yzdt5ig
L6Qn1dbhTZmqmV4nKhDb6pBrTdb8aMXO5LckotivF4H8h5TRUdbXraPi2+rbf5SN
5/b30zuCr5ODUjW942B8KKyvSxRGs96N2M5R4ThxdIw6cfYV/pAh2UOnFmrRroeB
UbvmCRx8HardZuMoffXzXV00VQKBgQDPkKu5ZxMTqIU/dPzYDxRMgWPHQETuOThr
K6LjsjdXohNGAKrG5eiJrfUz8WUOCC90xSBqw72vL7pgY64bgPxvJTUWyfRFeBfS
7uwyuZYREmFmg3UkuzGNnX3Q+PHO/d+wlDKWj/PtR7B8yM1/D5cw2NG6sR1pJTqS
Gb6bry4dNQKBgQCScMqaJIp/1aPnkkHRXxJTs9D8783n4X9zWsiPwBSYJKEUNJCO
UzC4YoiNMDQk/sbyfEwqvtCJCZHHUWRv4BusIbyfpsysTzylAF3Aq1zvzmokHBhA
LU0SVLzoyo1bKzslB1a5Ti2N1oXfCl1IApaoPeWRWQSCv8SqxDgDfvOJ1QKBgQCg
fEtKXtfxKytblSiqJX6caK6tMJQbXUKyGlsnknQX3cjpJzrj7n+NdGNSdiKcZtfK
gWA/LHlNKqoAPRIxUdncVfhmVl/4FpLVFMarsbLGIGAO0zWP4Oy/gjX1jYXpdYGv
FebHYyZHIFblJJ0+0N8ldX8zyh3jXlWbASzPUvNkwQKBgQC8Dmo8rATm8xiwixvE
YVLrv16cvtK3yoIjN90KXM5vr8Q40GxPvPWtyGjC1DVpTx8qBVRF4DAopVVNBSa5
XsJyuM67fehC8iwAVW0jUYly4l4df3b/Te74a0EkTgUjBXz5ndviODWcU8iVbZxN
K8hHLs0wTukQb665+CiYDzJ9eQ==
-----END PRIVATE KEY-----
"""
client_email = "bigbasket-sheets-api@sptpl-452205.iam.gserviceaccount.com"
client_id = "104103951866891127750"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/bigbasket-sheets-api%40sptpl-452205.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
